
[build]
  command = "npm run build"
  publish = "dist"

# Gérer le routage SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Contrôle du cache pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Variables d'environnement qui peuvent être définies dans l'interface Netlify
[build.environment]
  VITE_APP_ENV = "production"
  NODE_VERSION = "18"
