
[build]
  command = "NODE_ENV=production npm run build"
  publish = "dist"

# Single Page Application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables
[build.environment]
  VITE_APP_ENV = "production"
  NODE_VERSION = "18"
  NODE_ENV = "production"
  # Placeholder environment variables (will be overridden in Netlify UI)
  VITE_SUPABASE_URL = "placeholder"
  VITE_SUPABASE_ANON_KEY = "placeholder"
